(function(root){'use strict';
 const F=Fog,C=Chronicles,D=ChroniclesData,H=HubStore,results=[];
 const good=()=>2,seq=(a,f=2)=>()=>a.length?a.shift():f;
 const clone=x=>JSON.parse(JSON.stringify(x));
 const assert=(x,m='Assertion failed')=>{if(!x)throw Error(m);};
 const equal=(x,y)=>assert(JSON.stringify(x)===JSON.stringify(y),JSON.stringify(x)+' != '+JSON.stringify(y));
 const throws=f=>{let bad=false;try{f();}catch(e){bad=true;}assert(bad,'Expected rejection');};
 const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
 const build=(p=1,job='detective')=>({preset:p,job,name:'測試調查員',background:'記錄實際發生的事。',...F.allocate(p,job)});
 function runScene(s,sc,choice=0,all=true){C.travel(s,sc.id);assert(s.scene===sc.id,'scene not reachable');C.act(s,'examine',good);C.act(s,'question_0',good);if(all)C.act(s,'question_1',good);C.act(s,'careful',good);assert(!s.ending,'unexpected ending');C.act(s,'resolve_'+choice,good);assert(C.memory(s,sc.id).resolved,'not resolved');if(all){const f=C.options(s).find(x=>x.id.startsWith('follow_'));if(f)C.act(s,f.id,good);}C.validate(clone(s));}
 function campaign(id,route='public',preset=1,job='detective',choice=0,prior=[]){const s=C.newGame(id,build(preset,job),prior,good);const data=D.stories[id];for(let a=0;a<3;a++){for(const sc of data.scenes.filter(x=>x.act===a))runScene(s,sc,choice);const q=data.deductions[a],proof=q.evidence.find(k=>s.clues.includes(k));assert(C.deduce(s,q.id,q.answer,proof).ok,'deduction failed');assert(C.advance(s),'advance failed');C.validate(clone(s));}assert(C.chooseRoute(s,route));for(let i=0;i<3;i++){assert(C.finaleAction(s,'brief',good));assert(C.finaleAction(s,'insight',good));C.validate(clone(s));}assert(s.ending?.type==='success','did not finish');return s;}
 for(const data of Object.values(D.stories).filter(d=>d.id!=='theatre')){
  test(data.title+'：12地點、6人物、4支線且引用完整',()=>{equal(data.scenes.length,12);equal(data.npcs.length,6);equal(data.followups.length,4);equal(new Set(data.scenes.map(x=>x.id)).size,12);for(const sc of data.scenes){assert(data.npcs.some(n=>n.id===sc.npc));assert(F.SKILLS[sc.skill]);equal(sc.questions.length,2);equal(sc.choices.length,2);assert(sc.opening.length>100&&sc.document.length>90);}for(const f of data.followups)assert(data.scenes.some(x=>x.id===f.scene));for(const q of data.deductions){assert(q.answer>=0&&q.answer<q.options.length);q.evidence.forEach(k=>assert(data.scenes.some(x=>x.id===k)));}});
  for(let p=0;p<3;p++)for(const job of Object.keys(F.JOBS))for(const route of ['public','sealed','broken'])test(data.title+`：完整路線 ${p}/${job}/${route}`,()=>{const s=campaign(data.id,route,p,job);equal(s.ending.route,route);equal(s.clues.length,12);assert(s.actionCount>=70);C.validate(clone(s));});
  test(data.title+'：相反立場有不同旗標與結果',()=>{const a=campaign(data.id,'public',1,'detective',0),b=campaign(data.id,'public',1,'detective',1);assert(JSON.stringify(a.flags)!==JSON.stringify(b.flags));assert(JSON.stringify(a.ending.consequences)!==JSON.stringify(b.ending.consequences));});
  test(data.title+'：安全調查與最低探索路線可完成',()=>{const s=C.newGame(data.id,build(),[],good);for(let a=0;a<3;a++){const q=data.deductions[a],scenes=data.scenes.filter(x=>x.act===a);const selected=scenes.slice(0,3);const required=scenes.find(x=>q.evidence.includes(x.id));if(required&&!selected.includes(required))selected[2]=required;for(const sc of selected)runScene(s,sc,0,false);const proof=q.evidence.find(k=>s.clues.includes(k));assert(C.deduce(s,q.id,q.answer,proof).ok);assert(C.advance(s));}C.chooseRoute(s,'sealed');for(let i=0;i<3;i++){C.finaleAction(s,'brief',good);C.finaleAction(s,'insight',good);}equal(s.ending.type,'success');equal(s.clues.length,9);});
 }
 test('不可以未取得證物就推論',()=>{const s=C.newGame('asylum',build(),[],good);assert(!C.deduce(s,'identity',1,'ward').ok);});
 test('錯誤推論不刪除證物',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);assert(!C.deduce(s,'identity',0,'register').ok);assert(s.clues.includes('register'));});
 test('同一推論不可重複領洞見',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.deduce(s,'identity',1,'register');const before=s.insight;C.deduce(s,'identity',1,'register');equal(s.insight,before);});
 test('未開放章節不可直接移動',()=>{const s=C.newGame('train',build(),[],good);assert(!C.travel(s,'control'));equal(s.scene,'ticket');});
 test('地點不可跳過交談和驗證就作立場決定',()=>{const s=C.newGame('asylum',build(),[],good);assert(!C.act(s,'resolve_0',good));C.act(s,'examine',good);assert(!C.act(s,'resolve_0',good));});
 test('互斥立場不可重選或重複加資源',()=>{const s=C.newGame('tide',build(),[],good);runScene(s,D.stories.tide.scenes[0]);const before=clone(s);C.act(s,'resolve_1',good);equal(s,before);});
 test('回訪支線由旗標開啟並只領一次',()=>{const s=C.newGame('asylum',build(),[],good),sc=D.stories.asylum.scenes.find(x=>x.id==='ward');runScene(s,sc,0,false);const opt=C.options(s).find(x=>x.id==='follow_gu_letter_0');assert(opt);C.act(s,opt.id,good);assert(s.followups.includes('gu_letter'));const before=clone(s);C.act(s,opt.id,good);equal(s,before);});
 test('失敗後不能用放棄重置普通擲骰',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.act(s,'investigate',seq([1,8]));assert(s.pending);C.act(s,'abandon',good);assert(!C.options(s).some(x=>x.id==='investigate'));assert(C.options(s).some(x=>x.id==='careful'));});
 test('孤注一擲期間不能換地點',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.act(s,'investigate',seq([1,8]));assert(!C.travel(s,'ward'));C.validate(clone(s));});
 test('孤注一擲成功得到洞見',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.act(s,'investigate',seq([1,8]));const before=s.insight;C.act(s,'push',good);equal(s.insight,before+1);});
 test('孤注一擲失敗造成事先說明的後果',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.act(s,'investigate',seq([1,8]));C.act(s,'push',seq([1,8,2]));equal(s.player.hp,9);assert(s.exposure>=2);assert(!s.pending);});
 function fight(){const s=C.newGame('asylum',build(),[],good);s.chapter=2;C.travel(s,'oldwing');C.act(s,'examine',good);C.act(s,'investigate',seq([1,8]));C.act(s,'push',seq([1,8,2,2]));assert(s.combat);return s;}
 test('危機後能使用支援逃離並完成同一地點',()=>{const s=fight();C.combat(s,'supportEscape',good);assert(!s.combat);C.act(s,'question_0',good);C.act(s,'resolve_0',good);assert(s.visits.oldwing.resolved);});
 test('戰鬥有獨立防守階段與彈藥',()=>{const s=fight();C.combat(s,'shoot',good);equal(s.player.ammo,5);equal(s.combat.phase,'defense');const before=clone(s);C.combat(s,'shoot',good);equal(s,before);C.combat(s,'dodge',good);equal(s.combat.phase,'player');C.validate(clone(s));});
 test('瀕死狀態可保存並由同伴急救',()=>{const s=fight();s.player.hp=1;s.player.major=true;C.combat(s,'shoot',seq([1,8,1,5]));s.combat.incoming=2;C.combat(s,'dodge',seq([1,8,2]));assert(s.flags.dying);C.validate(clone(s));C.dying(s,'aid',good);equal(s.player.hp,1);assert(!s.flags.dying);});
 test('完整前案影響可帶入下一部',()=>{const a=campaign('asylum');const t=C.newGame('train',build(),[a],good);equal(t.history.length,1);assert(t.support>3);C.validate(clone(t));});
 test('不帶入未完成的前案',()=>{const a=C.newGame('asylum',build(),[],good);const t=C.newGame('train',build(),[a],good);equal(t.history.length,0);});
 test('不能把後案影響帶回早年',()=>{const t=campaign('train');const a=C.newGame('asylum',build(),[t],good);equal(a.history.length,0);});
 test('列車寄出的警告有實際第三部支援效果',()=>{const t=campaign('train');assert(t.flags.coast_informed);const s=C.newGame('tide',build(),[t],good);assert(s.support>=5);assert(s.log.some(l=>l.text.includes('鄭采文')));});
 test('返回章節地圖保留既有紀錄',()=>{const s=C.newGame('asylum',build(),[],good);for(const sc of D.stories.asylum.scenes.slice(0,3))runScene(s,sc);C.deduce(s,'identity',1,'ward');C.advance(s);assert(C.travel(s,'ward'));assert(s.visits.ward.resolved);});
 test('終局須完成三次核對和三次操作',()=>{const s=campaign('asylum');equal(s.finale.step,3);const before=clone(s);C.finaleAction(s,'insight',good);equal(s,before);});
 test('不同劇本存檔不會互相覆蓋',()=>{const h=H.empty(),p=H.create(h,'A','a');p.saves.asylum=C.newGame('asylum',build(),[],good);p.saves.train=C.newGame('train',build(),[],good);H.validate(h);equal(Object.keys(p.saves).length,2);});
 test('不同調查員的存檔隔離',()=>{const h=H.empty(),a=H.create(h,'A','a');a.saves.asylum=C.newGame('asylum',build(),[],good);H.create(h,'B','b');assert(!H.active(h).saves.asylum);h.active='a';assert(H.active(h).saves.asylum);});
 test('舊版霧港存檔可與長篇共同保管',()=>{const h=H.empty(),p=H.create(h,'A','a');p.saves.fog=F.newGame(build(),good);p.saves.asylum=C.newGame('asylum',build(),[],good);H.validate(clone(h));});
 test('拒絕存檔劇本與欄位不一致',()=>{const h=H.empty(),p=H.create(h,'A','a');p.saves.train=C.newGame('asylum',build(),[],good);throws(()=>H.validate(h));});
 test('拒絕惡意劇本名稱',()=>{const s=C.newGame('asylum',build(),[],good);s.story='constructor';throws(()=>C.validate(s));});
 test('拒絕不完整玩家職業',()=>{const s=C.newGame('asylum',build(),[],good);s.player.job='invalid';throws(()=>C.validate(s));});
 test('拒絕不完整骰子欄位',()=>{const s=C.newGame('asylum',build(),[],good);C.act(s,'examine',good);C.act(s,'investigate',good);delete s.rolls[0].tens;throws(()=>C.validate(s));});
 test('拒絕偽造完成地點但沒有證物',()=>{const s=C.newGame('asylum',build(),[],good);s.visits.register.resolved=true;throws(()=>C.validate(s));});
 test('拒絕無限或負值資源',()=>{const s=C.newGame('asylum',build(),[],good);s.support=Infinity;throws(()=>C.validate(s));});
 test('90條隨機探索、戰鬥與撤退可保存並收束',()=>{for(let seed=1;seed<=90;seed++){let n=seed;const rng=max=>{n=(n*1664525+1013904223)>>>0;return n%max+1;},id=Object.keys(D.stories)[seed%3],s=C.newGame(id,build(seed%3,Object.keys(F.JOBS)[seed%3]),[],rng);for(let step=0;step<130&&!s.ending;step++){if(s.flags.dying){if(s.support>0&&!s.flags.dying_aid)C.dying(s,'aid',rng);else C.dying(s,'wait',rng);}else if(s.pending)C.act(s,rng(2)===1?'push':'abandon',rng);else if(s.combat)C.combat(s,s.combat.phase==='defense'?'dodge':s.support?'supportEscape':'escape',rng);else if(step>100)C.evacuate(s,rng);else{const opts=C.options(s);if(opts.length&&rng(3)>1)C.act(s,opts[rng(opts.length)-1].id,rng);else{const loc=D.stories[id].scenes.filter(x=>x.act<=s.chapter);C.travel(s,loc[rng(loc.length)-1].id);}}C.validate(clone(s));}assert(s.ending,'seed '+seed+' did not finish');}});
 root.ChroniclesTests=results;
 if(typeof document!=='undefined'){const el=document.getElementById('test-results');if(el){el.textContent=results.map(r=>(r.pass?'PASS ':'FAIL ')+r.name+(r.error?' — '+r.error:'')).join('\n');document.getElementById('test-summary').textContent=`${results.filter(r=>r.pass).length}/${results.length} 通過`;}}
 if(typeof module!=='undefined'&&module.exports)module.exports=results;
})(globalThis);
