(function(root){
 'use strict';
 const F=root.Fog,D=root.ChroniclesData,VERSION=2;
 const own=(o,k)=>Object.hasOwn(o,k),clone=x=>JSON.parse(JSON.stringify(x));
 const MAX_LOG=650;
 function story(s){return D.stories[s.story];}
 function location(s){return story(s).scenes.find(x=>x.id===s.scene);}
 function add(s,text,type='story'){s.log.push({type,text,chapter:s.chapter,at:s.time});if(s.log.length>MAX_LOG)s.log.shift();}
 function memory(s,id){return s.visits[id]||(s.visits[id]={examined:false,questions:[],investigated:false,attempted:false,resolved:false,choice:null,risk:false});}
 function snapshotPrior(prior){return (prior||[]).filter(x=>x&&['asylum','train','tide'].includes(x.story)&&x.ending).map(x=>({story:x.story,title:D.stories[x.story].title,route:x.ending.route||'escape',trust:x.trust,flags:clone(x.flags),endingTitle:x.ending.title}));}
 function newGame(id,build,prior=[],rng=F.randomInt){if(!own(D.stories,id))throw Error('找不到劇本。');const p=F.newGame(build,rng).player,history=snapshotPrior(prior).filter(x=>D.stories[x.story].order<D.stories[id].order);const s={version:VERSION,story:id,build:clone(build),player:p,chapter:0,scene:D.stories[id].scenes[0].id,time:480,visits:{},clues:[],met:[],flags:{},support:3,insight:3,trust:0,exposure:0,log:[],rolls:[],notes:'',deductions:[],followups:[],combat:null,pending:null,finale:null,ending:null,history,healthCare:{},horrorSeen:[],actionCount:0,activeMs:0};
  add(s,D.stories[id].prologue.join('\n\n'),'opening');
  if(history.length){add(s,'前案留下的影響：'+history.map(h=>`${h.title}以「${h.endingTitle}」收束。${h.route==='public'?'公開的資料使委託人已知道你的名字。':h.route==='sealed'?'共同保管的承諾使你被要求再次說明設備的去向。':h.route==='broken'?'被拆除的裝置讓研究會重新安排了這裡的負載。':'前案未竟的工作仍被當事人記得。'}`).join('\n'),'legacy');if(history.some(h=>h.trust>=6))s.support++;if(history.some(h=>h.route==='public'))s.insight++;if(history.some(h=>h.route==='broken'))s.exposure++;}
  if(id==='tide'&&history.some(h=>h.flags.coast_informed)){s.support++;add(s,'鄭采文已收到你在列車寄出的可核對警告。廣播台提前準備了居民聯络資料，支援增加1。','legacy');}
  if(id==='train'&&history.some(h=>h.flags.rail_origin)){s.insight++;add(s,'白榆保存的原型編號能與行李車直接核對，洞見增加1。','legacy');}
  enter(s,s.scene);return s;
 }
 function enter(s,id){s.scene=id;const sc=location(s);memory(s,id);if(!s.met.includes(sc.npc))s.met.push(sc.npc);add(s,sc.name+'\n'+sc.opening,'scene');}
 function tick(s,n){const before=Math.floor(s.time/1440);s.time+=n;if(Math.floor(s.time/1440)>before){s.player.daySan=Math.max(1,s.player.san);s.player.sanLost=0;add(s,'新的一日。理智損失改以今日起始值計算，已發生的選擇仍然保留。','event');}if(s.time%1440>=1260&&!s.flags['late_'+Math.floor(s.time/1440)]){s.flags['late_'+Math.floor(s.time/1440)]=true;s.exposure=Math.min(10,s.exposure+1);add(s,'夜班接替了白天的人。調查仍可繼續，但你的活動更容易被注意。沒有因為閱讀文字而流逝的隱藏倒數。','event');}s.actionCount++;}
 function effect(s,e){for(const k of ['support','insight','trust','exposure'])if(e[k])s[k]=Math.max(k==='trust'?-12:0,Math.min(k==='exposure'?10:40,s[k]+e[k]));if(e.flag)s.flags[e.flag]=true;}
 function check(s,key,label,difficulty=1,rng=F.randomInt,extra=0){const value=own(s.player.attrs,key)?s.player.attrs[key]:s.player.skills[key];let mod=extra+(!own(s.player.attrs,key)&&root.Pressure?root.Pressure.penalty(s):0);if(s.player.insaneUntil>s.time||s.player.indefinite)mod--;return F.check(s,value,label,difficulty,Math.max(-2,Math.min(2,mod)),rng);}
 function sanity(s,id,max,rng){if(s.horrorSeen.includes(id))return;s.horrorSeen.push(id);const r=F.check(s,s.player.san,'理智：'+location(s).name,1,0,rng),loss=r.success?0:r.grade<0?max:F.dice(1,max,rng);s.player.san=Math.max(0,s.player.san-loss);s.player.sanLost+=loss;add(s,`理智損失 ${loss}；SAN ${s.player.san}。`,loss?'danger':'story');if(!s.player.san){end(s,'madness',rng);return;}if(s.player.sanLost>=Math.floor(s.player.daySan/5)){s.player.indefinite=true;add(s,'不定性瘋狂：此章以清醒間歇繼續調查；專注檢定受懲罰。你仍可安全撤離。','danger');}if(loss>=5&&check(s,'INT','理解恐怖',1,rng).success){s.player.insaneUntil=s.time+F.dice(1,10,rng)*60;tick(s,F.dice(1,10,rng));add(s,'暫時瘋狂：你躲到熟悉的物件旁，待聲音不再蓋過當下才重新行動。接下來的專注檢定暫受懲罰（本作發作簡化）。','danger');}}
 function hurt(s,amount,rng){const p=s.player,was=p.major,r=F.damageState(p.hp,p.maxHp,p.major,amount);p.hp=r.hp;p.major=r.major;add(s,`受到 ${amount} 點傷害，HP ${p.hp}/${p.maxHp}。`,'danger');if(r.dead){end(s,'death',rng);return;}if(!p.hp){if(p.major){s.combat=null;s.pending=null;s.flags.dying=true;s.flags.dying_aid=false;add(s,'你因重傷陷入瀕死。每次等待救援都需要CON檢定；若還有支援，可請同伴嘗試急救。','danger');}else end(s,'unconscious',rng);return;}if(amount>=p.maxHp/2&&!check(s,'CON','重傷：保持清醒',1,rng).success)end(s,'unconscious',rng);}
 function blocked(s){return !!(s.ending||s.combat||s.pending||s.finale||s.flags.dying);}
 function travel(s,id){if(blocked(s))return false;const sc=story(s).scenes.find(x=>x.id===id&&x.act<=s.chapter);if(!sc||id===s.scene)return false;tick(s,15);enter(s,id);return true;}
 function investigationSkills(sc){return [...new Set([sc.skill,...(sc.altSkills||[])])];}
 function enemy(s){return story(s).enemies?.[s.combat?.enemy]||story(s).enemy;}
 function options(s){if(blocked(s))return [];const sc=location(s),v=memory(s,sc.id),out=[];if(!v.examined)out.push({id:'examine',title:'查訪並抄錄：'+sc.evidence,hint:'取得核心證物，不需擲骰 · 20分鐘'});sc.questions.forEach((q,i)=>{if(!v.questions.includes(i))out.push({id:'question_'+i,title:q[0],hint:'深入交談 · 15分鐘'});});if(v.examined&&!v.investigated){if(!v.attempted)investigationSkills(sc).forEach((key,i)=>out.push({id:i?'investigate_'+key:'investigate',title:'深入調查：'+F.SKILLS[key][0],hint:`${F.SKILLS[key][0]} ${s.player.skills[key]} · 成功增加洞見；失敗不遺失證物 · 20分鐘`}));out.push({id:'careful',title:'花時間請當事人逐項核對',hint:'不用擲骰，確保完成；沒有額外洞見 · 45分鐘'});}if(v.examined&&v.questions.length&&v.investigated&&!v.resolved)sc.choices.forEach((c,i)=>out.push({id:'resolve_'+i,title:c[0],hint:effectsText(c[2])+' · 本地點只能選一個立場 · 20分鐘'}));for(const f of story(s).followups||[])if(f.scene===s.scene&&!s.followups.includes(f.id)&&f.requires.some(k=>s.flags[k]))f.choices.forEach((c,i)=>{if((c[2].support||0)<-s.support)return;out.push({id:'follow_'+f.id+'_'+i,title:c[0],hint:effectsText(c[2])+' · 支線立場 · 25分鐘',context:i===0?f.title+'\n\n'+f.intro:''});});return out;}
 function effectsText(e){const names={support:'支援',insight:'洞見',trust:'信任',exposure:'警戒'};return Object.keys(names).filter(k=>e[k]).map(k=>names[k]+(e[k]>0?'+':'')+e[k]).join(' / ');}
 function investigate(s,rng,pushed=false,key=location(s).skill){const sc=location(s),v=memory(s,sc.id);v.attempted=true;const r=check(s,key,F.SKILLS[key][0]+'：'+sc.evidence,1,rng);if(r.success){v.investigated=true;v.risk=true;effect(s,{insight:1});add(s,sc.success,'discovery');if(sc.horror)sanity(s,sc.id,sc.horror,rng);}else{add(s,sc.failure,'story');if(pushed||r.grade===-1){v.investigated=true;effect(s,{exposure:2});if(pushed&&sc.enemy)startCombat(s,rng);else if(pushed)hurt(s,F.dice(1,3,rng),rng);else add(s,'大失敗引起注意，但核心證物已保留。可繼續選擇本地點的立場。','danger');}else{s.pending={scene:sc.id,skill:key};add(s,'可孤注一擲：再花20分鐘，失敗將增加2警戒，並'+(sc.enemy?'引來異常存在。':'受到1D3傷害。')+'也可以接受結果，改用慢速核對。','warning');}}}
 function act(s,id,rng=F.randomInt){if(s.ending||s.combat||s.finale||s.flags.dying)return false;
  if(s.pending){if(!['push','abandon'].includes(id))return false;const retrySkill=s.pending.skill||location(s).skill;s.pending=null;if(id==='abandon'){add(s,'你接受這次失敗。核心證物仍在，可以改用較慢的核對方式。');return true;}tick(s,20);investigate(s,rng,true,retrySkill);return true;}
  if(!options(s).some(x=>x.id===id))return false;const sc=location(s),v=memory(s,sc.id);
  if(id.startsWith('follow_')){const i=Number(id.slice(-1)),key=id.slice(7,-2),f=story(s).followups.find(x=>x.id===key);if(!f)return false;tick(s,25);s.followups.push(key);effect(s,f.choices[i][2]);add(s,f.title+'\n\n'+f.intro+'\n\n'+f.choices[i][0]+'\n'+f.choices[i][1],'choice');return true;}
  if(id==='examine'){tick(s,20);v.examined=true;if(!s.clues.includes(sc.id))s.clues.push(sc.id);add(s,sc.evidence+'\n\n'+sc.document,'document');}
  else if(id.startsWith('question_')){const i=Number(id.slice(-1));tick(s,15);v.questions.push(i);add(s,sc.questions[i][0]+'\n\n'+sc.questions[i][1],'dialogue');}
  else if(id==='investigate'||id.startsWith('investigate_')){tick(s,20);investigate(s,rng,false,id==='investigate'?sc.skill:id.slice(12));}
  else if(id==='careful'){tick(s,45);v.investigated=true;add(s,'你與當事人逐項核對，不把未能確認的部分寫成定論。\n\n'+sc.success,'discovery');if(sc.horror)sanity(s,sc.id,Math.min(3,sc.horror),rng);}
  else if(id.startsWith('resolve_')){const i=Number(id.slice(-1));tick(s,20);v.resolved=true;v.choice=i;effect(s,sc.choices[i][2]);add(s,sc.choices[i][0]+'\n\n'+sc.choices[i][1]+'\n'+effectsText(sc.choices[i][2]),'choice');}
  return true;
 }
 function chapterProgress(s){const scenes=story(s).scenes.filter(x=>x.act===s.chapter);return {resolved:scenes.filter(x=>s.visits[x.id]?.resolved).length,total:scenes.length,deduced:s.deductions.includes(story(s).deductions[s.chapter].id)};}
 function deduce(s,id,answer,evidence){if(blocked(s))return {ok:false,message:'請先處理目前的行動。'};const d=story(s).deductions.find(x=>x.id===id&&x.act<=s.chapter);if(!d||s.deductions.includes(id)||!s.clues.includes(evidence))return {ok:false,message:'請選擇一份你已取得的證物。'};tick(s,10);if(answer!==d.answer||!d.evidence.includes(evidence)){add(s,'這個推論尚未由所選證物支持。回到原文核對：結論需要同時對得上內容與來源。','warning');return {ok:false,message:'結論或證據不匹配；原證物仍保留，可重新核對。'};}s.deductions.push(id);s.insight=Math.min(40,s.insight+2);add(s,'推論完成：'+d.question+'\n'+d.explain,'deduction');return {ok:true,message:'證物支持此推論，獲得2洞見。'};}
 function advance(s){if(blocked(s))return false;const p=chapterProgress(s);if(p.resolved<3||!p.deduced)return false;if(s.chapter===2){s.finale={route:null,step:0,failures:0,briefed:false};add(s,story(s).finale.intro,'opening');return true;}s.chapter++;const nextDay=(Math.floor(s.time/1440)+1)*1440+480;tick(s,nextDay-s.time);if(!s.player.major)s.player.hp=Math.min(s.player.maxHp,s.player.hp+1);s.player.mp=s.player.maxMp;add(s,story(s).chapters[s.chapter].title+'\n'+story(s).chapters[s.chapter].text,'opening');add(s,'你休息至翌日。普通傷勢自然回復1 HP，魔力補滿；理智與重傷不會因此自動復原。','event');enter(s,story(s).scenes.find(x=>x.act===s.chapter).id);return true;}
 function rest(s,rng=F.randomInt){if(blocked(s)||s.healthCare[s.chapter]||s.support<1||s.player.hp>=s.player.maxHp)return false;s.healthCare[s.chapter]=true;s.support--;tick(s,20);const r=F.check(s,75,'同伴現場急救',1,0,rng);if(r.success){s.player.hp=Math.min(s.player.maxHp,s.player.hp+1);add(s,'傷口清理完成，回復1 HP。重傷仍需要後續醫療。');}else add(s,'急救未能恢復HP。同一章不反覆治療刷取效果。');return true;}
 function startCombat(s,rng=F.randomInt,key){if(s.ending||s.combat||s.flags.dying)return false;const e=story(s).enemies?.[key]||story(s).enemy;if(!e.human)sanity(s,s.scene,Math.max(3,location(s).horror||3),rng);if(s.ending)return false;s.combat={hp:e.hp,phase:'player',round:1,incoming:0,...(key?{enemy:key}:{})};add(s,e.name+'\n'+e.description,'danger');if(s.player.attrs.DEX<(e.dex||45)){s.combat.incoming=F.check(s,e.attack,e.name+'的先手攻擊',1,0,rng).grade;s.combat.phase='defense';add(s,'對方敏捷較高，先處理防守。','combat');}else add(s,'你先行動，可以攻擊或撤退。','combat');return true;}
 function db(s,rng,max=false){return s.player.db<=0?s.player.db:max?s.player.db:F.dice(1,s.player.db,rng);}
 function combat(s,id,rng=F.randomInt){const c=s.combat;if(!c||s.ending)return false;const e=enemy(s),p=s.player;
  if(c.phase==='defense'){if(!['dodge','counter'].includes(id))return false;const r=check(s,id==='dodge'?'dodge':'brawl',id==='dodge'?'閃避':'反擊',1,rng),result=F.melee(c.incoming,r.grade,id==='dodge'?'dodge':'fight');if(result==='attacker')hurt(s,c.incoming>=3?e.damage:F.dice(1,e.damage,rng),rng);else if(result==='defender'){const amount=Math.max(0,F.dice(1,6,rng)+db(s,rng)-e.armor);c.hp-=amount;add(s,`反擊造成 ${amount} 傷害。`,'combat');}else add(s,'攻擊未造成傷害。','combat');if(s.ending||s.flags.dying)return true;if(c.hp<=0){s.combat=null;add(s,e.human?'對方失去戰意，停止攻擊。你可以繼續調查。':'異常存在失去形體；你仍需回到調查與選擇。','combat');}else{c.phase='player';c.round++;tick(s,1);}return true;}
  if(!['attack','shoot','escape','supportEscape'].includes(id)||id==='shoot'&&!p.ammo||id==='supportEscape'&&s.support<1)return false;
  if(id==='supportEscape'){s.support--;s.combat=null;tick(s,10);add(s,'同伴與你關閉厚門，避開追擊。此地點的調查紀錄仍保留。');return true;}
  if(id==='escape'){const r=check(s,'dodge','離開追擊區',1,rng);if(r.success){s.combat=null;tick(s,10);add(s,'你沿已知通道撤出追擊範圍，重新整理調查。');return true;}}
  else{const shot=id==='shoot';if(shot)p.ammo--;const r=check(s,shot?'handgun':'brawl',shot?'單發左輪射擊':'短棍攻擊',1,rng);let hit=r.success;if(!shot){const d=F.check(s,e.dodge,'對方閃避',1,0,rng);hit=F.melee(r.grade,d.grade,'dodge')==='attacker';}if(hit){const amount=Math.max(0,(shot?(r.grade>=3?10+F.dice(1,10,rng):F.dice(1,10,rng)):(r.grade>=3?6+db(s,rng,true):F.dice(1,6,rng)+db(s,rng)))-e.armor);c.hp-=amount;add(s,`命中，扣除護甲後造成 ${amount} 傷害。`,'combat');}else add(s,'攻擊未能命中。','combat');if(c.hp<=0){s.combat=null;add(s,'追擊終止。你保留了先前的核心證物。');return true;}}
  const er=F.check(s,e.attack,e.name+'的攻擊',1,0,rng);c.incoming=er.grade;c.phase='defense';return true;
 }
 function dying(s,id,rng=F.randomInt){if(!s.flags.dying||s.ending||!['aid','wait'].includes(id))return false;
  if(id==='aid'){if(s.support<1||s.flags.dying_aid)return false;s.support--;s.flags.dying_aid=true;const r=F.check(s,75,'同伴穩定瀕死傷勢',1,0,rng);if(r.success){s.flags.dying=false;s.player.hp=1;add(s,'同伴暫時穩定了你的傷勢。立即撤離是合理的選擇。','warning');return true;}}
  tick(s,1);if(!check(s,'CON','瀕死：等待救援',1,rng).success)end(s,'death',rng);else add(s,'你仍活著，但無法自行行動。可等待下一次檢定，或以本次失敗結局收束。','danger');return true;
 }
 function chooseRoute(s,id){if(!s.finale||s.ending||s.flags.dying||s.combat||s.finale.route||!story(s).finale.routes.some(r=>r.id===id))return false;s.finale.route=id;add(s,'你選擇：'+story(s).finale.routes.find(r=>r.id===id).name,'choice');return true;}
 function finaleAction(s,method,rng=F.randomInt){const f=s.finale;if(!f||!f.route||s.combat||s.ending||s.flags.dying)return false;const route=story(s).finale.routes.find(r=>r.id===f.route);if(method==='brief'){if(f.briefed)return false;f.briefed=true;tick(s,10);add(s,'操作前核對：'+story(s).finale.tasks[f.step]+'\n'+story(s).deductions[f.step].explain+'\n參與者核對自己的位置與退出路線。你可以投入已驗證的洞見，請同伴支援，或親自承擔檢定風險。','briefing');return true;}if(!f.briefed||!['insight','support','skill'].includes(method))return false;if(method==='insight'&&s.insight<2||method==='support'&&s.support<2)return false;tick(s,20);let success=true;if(method==='insight'){s.insight-=2;add(s,'你按已驗證的推論與證物逐項執行，這一步不需擲骰。','discovery');}if(method==='support'){s.support-=2;add(s,'同伴分工並互相核對，支援確保這一步完成。','discovery');}if(method==='skill'){const r=check(s,route.skills[f.step],F.SKILLS[route.skills[f.step]][0]+'：'+story(s).finale.tasks[f.step],s.exposure>=8?2:1,rng);success=r.success;if(!success){f.failures++;s.exposure=Math.min(10,s.exposure+1);add(s,'這一步沒有完成，核心證物仍在。可以改用洞見或支援；三次失誤後，現場條件只允許撤離。','danger');if(r.grade<0)hurt(s,F.dice(1,3,rng),rng);}}
  if(s.ending||s.flags.dying)return true;if(f.failures>=3){end(s,'partial',rng);return true;}if(success){f.step++;f.briefed=false;if(f.step>=3)end(s,'success',rng);}return true;
 }
 function end(s,type,rng=F.randomInt){if(s.ending)return false;let title,text,reward=0,route=s.finale?.route||'escape';const data=story(s);if(type==='success'){const r=data.finale.routes.find(r=>r.id===route);title=r.name+'・'+(s.trust>=8?'有人共同見證':'仍待回答的承諾');text=data.finale.epilogues[route];reward=F.dice(1,s.trust>=8?6:3,rng);s.player.san=Math.min(99-s.player.skills.mythos,s.player.san+reward);}else if(type==='death'){title='檔案中的另一個名字';text='調查員未能離開現場。你已保存的證物與承諾沒有消失；下一位調查員可以從另一條路接近真相。';route='escape';}else if(type==='madness'){title='再也無法分辨的回聲';text='你失去了繼續調查的能力。這不是所有問題都已被回答，而是這位調查員的故事需要在這裡停止。';route='escape';}else if(type==='unconscious'){title='未竟的調查';text='傷勢讓你失去行動能力。同伴保住了已完成的紀錄，接下來的決定將由仍能行動的人面對。';route='escape';}else{title=type==='partial'?'代價尚未結清':'帶著證物撤離';text='你沒有完成全部操作，但把仍能帶走的人、證物與聯絡方式帶離危險。未完成的工作不是不存在；後續章節會記得這場調查留下的缺口。';route='escape';}s.ending={type,route,title,text,reward,consequences:consequences(s)};s.combat=null;s.pending=null;s.flags.dying=false;add(s,text,'ending');return true;}
 function consequences(s){const out=[];for(const sc of story(s).scenes){const v=s.visits[sc.id];if(v?.resolved)out.push({place:sc.name,choice:sc.choices[v.choice][0],result:sc.choices[v.choice][1]});}for(const f of story(s).followups||[])if(s.followups.includes(f.id)){const c=f.choices.find(x=>s.flags[x[2].flag]);if(c)out.push({place:f.title,choice:c[0],result:c[1]});}return out;}
 function evacuate(s,rng=F.randomInt){if(s.ending||s.combat||s.pending)return false;return end(s,s.flags.dying?'unconscious':'escape',rng);}
 function validate(s){F.migrateSkills(s);const bad=()=>{throw Error('劇本存檔格式不完整或不相容，原進度未被更動。');},int=(v,a,b)=>Number.isInteger(v)&&v>=a&&v<=b,str=(v,n)=>typeof v==='string'&&v.length<=n;
  if(!s||s.version!==VERSION||!own(D.stories,s.story))bad();const data=story(s),ids=data.scenes.map(x=>x.id);if(!int(s.chapter,0,2)||!ids.includes(s.scene)||data.scenes.find(x=>x.id===s.scene).act>s.chapter||!int(s.time,480,999999))bad();
  try{F.validateBuild(s.build);}catch(e){bad();}const p=s.player,a=F.attributes(s.build.preset),d=F.derived(a),base=F.baseSkills(a);if(!p||p.job!==s.build.job||!str(p.name,24)||!str(p.background,400)||!p.attrs||F.ATTR.some(k=>p.attrs[k]!==a[k])||!p.skills||Object.keys(F.SKILLS).some(k=>p.skills[k]!==base[k]+s.build.occ[k]+s.build.interest[k]))bad();for(const k of Object.keys(d))if(p[k]!==d[k])bad();if(!int(p.hp,0,d.maxHp)||!int(p.san,0,99)||!int(p.mp,0,d.maxMp)||!int(p.ammo,0,6)||!int(p.luck,0,99)||!int(p.daySan,1,99)||!int(p.sanLost,0,9999)||!int(p.insaneUntil,0,999999)||typeof p.major!=='boolean'||typeof p.indefinite!=='boolean')bad();
  for(const k of ['clues','met','deductions','horrorSeen','followups'])if(!Array.isArray(s[k])||s[k].length>30||new Set(s[k]).size!==s[k].length)bad();if(s.clues.some(x=>!ids.includes(x))||s.met.some(x=>!data.npcs.some(n=>n.id===x))||s.deductions.some(x=>!data.deductions.some(d=>d.id===x))||s.horrorSeen.some(x=>!ids.includes(x))||s.followups.some(x=>!(data.followups||[]).some(f=>f.id===x)))bad();
  if(!s.visits||typeof s.visits!=='object'||Array.isArray(s.visits)||Object.keys(s.visits).some(k=>!ids.includes(k)))bad();for(const [k,v]of Object.entries(s.visits)){if(!v||['examined','investigated','attempted','resolved','risk'].some(f=>typeof v[f]!=='boolean')||!Array.isArray(v.questions)||v.questions.length>2||v.questions.some(x=>!int(x,0,1))||v.choice!==null&&!int(v.choice,0,1)||v.resolved&&(!v.examined||!v.investigated||!v.questions.length||v.choice===null)||v.examined!==s.clues.includes(k))bad();}
  for(const k of ['support','insight','trust','exposure'])if(!int(s[k],k==='trust'?-12:0,k==='exposure'?10:40))bad();if(!s.flags||typeof s.flags!=='object'||Array.isArray(s.flags)||Object.keys(s.flags).length>150||Object.entries(s.flags).some(([k,v])=>!/^[a-z0-9_]+$/.test(k)||['__proto__','constructor','prototype'].includes(k)||typeof v!=='boolean'))bad();
  if(!Array.isArray(s.log)||s.log.length>MAX_LOG||s.log.some(l=>!l||!str(l.text,20000)||!str(l.type,20)))bad();if(!Array.isArray(s.rolls)||s.rolls.length>100||s.rolls.some(r=>!r||!str(r.label,200)||!int(r.value,1,100)||!int(r.skill,0,100)||!int(r.target,0,100)||!int(r.mod,-2,2)||!int(r.grade,-1,4)||!int(r.unit,0,9)||typeof r.success!=='boolean'||!Array.isArray(r.tens)||r.tens.length!==1+Math.abs(r.mod)||r.tens.some(t=>!int(t,0,9))||!Array.isArray(r.candidates)||r.candidates.length!==r.tens.length||r.candidates.some(t=>!int(t,1,100))))bad();
  if(!str(s.notes,12000)||!int(s.actionCount,0,100000)||!Number.isFinite(s.activeMs)||s.activeMs<0||s.activeMs>1e12||!s.healthCare||Object.entries(s.healthCare).some(([k,v])=>!['0','1','2'].includes(k)||v!==true))bad();
  if(!Array.isArray(s.history)||s.history.length>2||s.history.some(h=>!h||!own(D.stories,h.story)||!['public','sealed','broken','escape'].includes(h.route)||!str(h.title,100)||!str(h.endingTitle,150)))bad();
  if(s.pending&&(!ids.includes(s.pending.scene)||s.pending.scene!==s.scene||s.pending.skill&&!investigationSkills(location(s)).includes(s.pending.skill)))bad();if(s.combat&&(!int(s.combat.hp,1,enemy(s).hp)||s.combat.enemy&&!Object.hasOwn(data.enemies||{},s.combat.enemy)||!['player','defense'].includes(s.combat.phase)||!int(s.combat.incoming,-1,4)||!int(s.combat.round,1,10000)))bad();if(s.finale&&(![null,'public','sealed','broken'].includes(s.finale.route)||!int(s.finale.step,0,3)||!int(s.finale.failures,0,3)||typeof s.finale.briefed!=='boolean'))bad();if(s.ending&&(!['success','death','madness','unconscious','partial','escape'].includes(s.ending.type)||!['public','sealed','broken','escape'].includes(s.ending.route)||!str(s.ending.title,150)||!str(s.ending.text,10000)||!int(s.ending.reward,0,6)||!Array.isArray(s.ending.consequences)||s.ending.consequences.length>16||s.ending.consequences.some(x=>!str(x.place,100)||!str(x.choice,300)||!str(x.result,2000))))bad();return s;
 }
 root.Chronicles={VERSION,enemy,startCombat,check,add,tick,effect,blocked,newGame,story,location,memory,options,act,travel,chapterProgress,deduce,advance,rest,combat,dying,chooseRoute,finaleAction,evacuate,validate,effectsText,consequences,clone};
})(globalThis);
