/* Presentation only: no game clock, rolls, inventory or save-state mutations. */
(function(root){
 'use strict';
 const doc=root.document,KEY='cthulhu-display-v1';
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icons={eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Z M9 3v16 M15 5v16"/>',book:'<path d="M4 3h13a3 3 0 0 1 3 3v15H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3 M7 3v14 M3 17h17"/>',settings:'<path d="M4 7h16 M4 17h16 M8 4v6 M16 14v6"/>',expand:'<path d="M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5"/>',heart:'<path d="M12 21 3.6 12.6a5.5 5.5 0 0 1 7.8-7.8l.6.6.6-.6a5.5 5.5 0 0 1 7.8 7.8L12 21Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',arrow:'<path d="M4 12h16 M14 6l6 6-6 6"/>'};
 function icon(name){return '<svg viewBox="0 0 24 24" class="ui-icon" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">'+(icons[name]||icons.eye)+'</svg>';}
 let current=null,prefs={text:'standard',contrast:false,dice:true},diceTimer=null,diceTicket=0,diceBatch=[],diceIndex=0;
 const observedRolls=new WeakMap();
 root.addEventListener('storage',event=>{if(event.key!==KEY)return;try{const x=JSON.parse(event.newValue||'null');if(!x)return;if(['standard','large','largest'].includes(x.text))prefs.text=x.text;prefs.contrast=x.contrast===true;prefs.dice=x.dice!==false;applyPrefs();if(!prefs.dice){++diceTicket;doc.querySelector('#dice-overlay[open]')?.close();}}catch(e){}});
 try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x){if(['standard','large','largest'].includes(x.text))prefs.text=x.text;prefs.contrast=x.contrast===true;prefs.dice=x.dice!==false;}}catch(e){}
 function applyPrefs(save=false){doc.documentElement.dataset.textSize=prefs.text;doc.documentElement.classList.toggle('high-contrast',prefs.contrast);if(save)try{localStorage.setItem(KEY,JSON.stringify(prefs));}catch(e){}doc.querySelectorAll('[data-text-size-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.textSizeChoice===prefs.text)));for(const key of ['contrast','dice'])doc.querySelectorAll('[data-cinema="'+key+'"]').forEach(button=>button.setAttribute('aria-pressed',String(prefs[key])));}
 function fullscreen(){if(root.parent!==root&&root.parent.Cinema){root.parent.Cinema.fullscreen();return;}if(root.chrome?.webview){root.chrome.webview.postMessage('toggle-fullscreen');return;}const task=doc.fullscreenElement?doc.exitFullscreen():doc.documentElement.requestFullscreen?.();if(task?.catch)task.catch(()=>{const status=doc.querySelector('#display-status');if(status)status.textContent='目前環境未允許全螢幕，可改用視窗最大化。';});}
 function settings(){let modal=doc.getElementById('display-options');if(!modal){modal=doc.createElement('dialog');modal.id='display-options';modal.innerHTML='<div class="dialog-toolbar"><span class="dialog-caption">顯示與閱讀</span><button class="close" data-cinema="close-settings" aria-label="關閉顯示設定">× 關閉</button></div><div class="dialog-body"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h2>用舒服的方式調查。</h2><p>調整文字大小與對比，不影響劇情、擲骰或遊戲時間。</p><fieldset><legend>閱讀字級</legend><div class="display-options"><button data-text-size-choice="standard">標準<span>18 px</span></button><button data-text-size-choice="large">大字<span>21 px</span></button><button data-text-size-choice="largest">特大<span>24 px</span></button></div></fieldset><button class="display-toggle" data-cinema="contrast" aria-pressed="false"><span>高對比閱讀<small>減少透明效果，強化文字與邊界。</small></span><span class="toggle-track" aria-hidden="true"></span></button><button class="display-toggle" data-cinema="fullscreen">'+icon('expand')+'切換全螢幕</button><p class="subtle">鍵盤快捷：I 開啟行動、M 地圖、J 紀錄。輸入文字或閱讀彈出視窗時不會觸發。</p><p id="display-status" role="status"></p></div>';doc.body.appendChild(modal);modal.addEventListener('click',ev=>{if(ev.target===modal){const r=modal.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)modal.close();}});}if(!modal.querySelector('[data-cinema="dice"]')){const toggle=doc.createElement('button');toggle.className='display-toggle';toggle.dataset.cinema='dice';toggle.innerHTML='<span>檢定擲骰動畫<small>顯示實際 D100、獎懲骰與結果；關閉後直接繼續。</small></span><span class="toggle-track" aria-hidden="true"></span>';modal.querySelector('fieldset').after(toggle);}applyPrefs();modal.showModal();}
 function header(){const bar=doc.querySelector('.topbar');if(!bar)return;if(!bar.querySelector('.display-button')){const button=doc.createElement('button');button.className='display-button';button.dataset.cinema='settings';button.innerHTML=icon('settings')+'<span>顯示設定</span>';button.setAttribute('aria-label','顯示設定：字級、對比與全螢幕');bar.appendChild(button);}const brand=doc.getElementById('hub-brand');if(brand&&!brand.dataset.restyled){brand.dataset.restyled='true';brand.innerHTML='<span class="brand-sigil" aria-hidden="true">◇</span><span class="brand-copy">克蘇魯的呼喚<small>調查員檔案室</small></span>';}}
 function die(label,value,selected=false){return '<div class="die-item '+(selected?'kept':'')+'"><div class="percentile-die"><svg viewBox="0 0 120 140" aria-hidden="true"><path d="M60 5 112 45 105 105 60 135 15 105 8 45Z"/><path d="M60 5 84 58 60 105 36 58Z M8 45 36 58 15 105 M112 45 84 58 105 105 M60 105v30 M15 105h90"/></svg><b data-face="'+value+'">?</b></div><span>'+label+'</span></div>';}
 function diceDialog(){let dialog=doc.getElementById('dice-overlay');if(!dialog){dialog=doc.createElement('dialog');dialog.id='dice-overlay';dialog.setAttribute('aria-label','百分骰檢定結果');doc.body.appendChild(dialog);dialog.addEventListener('close',()=>clearTimeout(diceTimer));}return dialog;}
 function finishAnimation(){clearTimeout(diceTimer);const dialog=doc.getElementById('dice-overlay');if(!dialog?.open)return;dialog.classList.remove('is-rolling');dialog.querySelectorAll('[data-face]').forEach(face=>face.textContent=face.dataset.face);dialog.querySelector('.roll-verdict').hidden=false;dialog.querySelector('.roll-verdict').setAttribute('aria-live','polite');dialog.querySelector('[data-cinema="skip-dice"]').hidden=true;const next=dialog.querySelector('[data-cinema="next-dice"]');next.hidden=false;next.focus();}
 function renderDice(){const dialog=diceDialog(),r=diceBatch[diceIndex],kept=r.candidates.indexOf(r.value);const tens=r.tens.map((n,i)=>die(r.tens.length===1?'十位骰':'十位骰 '+(i+1),String(n*10).padStart(2,'0'),i===kept)).join('');dialog.innerHTML='<div class="dialog-toolbar"><span class="dialog-caption">D100 · '+(diceIndex+1)+' / '+diceBatch.length+' 次檢定</span><button class="close" data-cinema="close-dice" aria-label="關閉擲骰結果">× 關閉</button></div><div class="dialog-body dice-body"><div class="eyebrow">THE DICE HAVE SPOKEN</div><h2>'+esc(r.label)+'</h2><div class="roll-target"><span>數值 <b>'+r.skill+'</b></span><span>成功門檻 <b>≤ '+r.target+'</b></span><span>'+(r.mod>0?r.mod+' 顆獎勵骰':r.mod<0?Math.abs(r.mod)+' 顆懲罰骰':'無獎懲骰')+'</span></div><div class="dice-stage" aria-hidden="true">'+tens+'<span class="dice-plus">＋</span>'+die('個位骰',String(r.unit),true)+'</div><div class="roll-verdict '+(r.success?'passed':'failed')+'" hidden><strong>'+String(r.value).padStart(2,'0')+'</strong><div><b>'+esc(Fog.gradeName(r.grade))+'</b><span>'+(r.success?'達成檢定要求':'未達本次檢定要求')+'</span></div></div><p class="roll-explanation">'+(r.mod>0?'共用個位骰，取最低完整結果。':r.mod<0?'共用個位骰，取最高完整結果。':'十位骰與個位骰合成百分骰。')+'候選：'+r.candidates.join('、')+'。'+(r.value===100?'00 ＋ 0 代表 100。':'')+'</p><div class="dice-controls"><button class="primary" data-cinema="skip-dice">略過動畫，查看結果</button><button class="primary" data-cinema="next-dice" hidden>'+(diceIndex<diceBatch.length-1?'下一個檢定 →':'繼續調查 →')+'</button><button data-cinema="disable-dice">關閉之後的擲骰動畫</button></div><p class="subtle dice-note">這是遊戲已記錄的檢定；略過或關閉不會重擲、不耗時間。</p></div>';dialog.classList.add('is-rolling');if(!dialog.open)dialog.showModal();const reduced=root.matchMedia('(prefers-reduced-motion: reduce)').matches;diceTimer=setTimeout(finishAnimation,reduced?0:900);}
 function observeDice(s){const seen=observedRolls.has(s),previous=observedRolls.get(s),last=s.rolls.at(-1)||null;observedRolls.set(s,last);const ticket=++diceTicket;if(!seen||!last||last===previous||!prefs.dice)return;const start=previous?s.rolls.indexOf(previous)+1:0;const batch=s.rolls.slice(start).map(r=>({...r,tens:[...r.tens],candidates:[...r.candidates]}));setTimeout(()=>{if(ticket!==diceTicket||current?.state!==s||!prefs.dice)return;diceBatch=batch;diceIndex=0;renderDice();},0);}
 function objective(s){
  if(s.ending)return {title:'調查已結束',text:'回顧你留下的選擇，閱讀完整故事脈絡。'};
  if(s.flags.dying)return {title:'你正處於瀕死狀態',text:'先處理傷勢。尋求同伴急救，或作出下一次體質檢定。'};
  if(s.combat)return {title:s.combat.phase==='defense'?'先處理對方的攻擊':'選擇戰鬥方式，或找機會撤退',text:'每個選項都列出技能與代價。撤退也能保留已取得的證據。'};
  if(s.pending)return {title:'決定是否孤注一擲',text:'再次嘗試有額外代價，也可以接受結果，換一個方法。'};
  if(Pressure.blocked(s))return {title:'先處理眼前的突發事件',text:'選擇冒險、使用物資，或承擔代價立即離開。'};
  if(s.story){const C=root.Chronicles,progress=C.chapterProgress(s),v=C.memory(s,s.scene);
   if(s.finale)return {title:s.finale.route?'完成終局的三個操作步驟':'選擇你要留下的結局',text:'可使用洞見、支援或技能完成操作；先看清各條路線的意義。'};
   if(progress.ready)return {title:'已完成本章，隨時可以前進',text:'下方可進入下一章；也可以留下補查支線，但仍會花費時間。'};
   if(!v.examined)return {title:'先核對現場證物',text:'取得核心證物不需擲骰。之後交談、深入調查，再決定你的立場。'};
   if(!v.questions.length)return {title:'聽聽當事人怎麼說',text:'選一個對話主題即可推進，也可以多問一些了解事件全貌。'};
   if(!v.investigated)return {title:'深入調查，驗證你的想法',text:'可用技能冒險檢定，或花更多時間慢速核對。'};
   if(!v.resolved)return {title:'決定你在這裡的立場',text:'這項選擇會留下後果。閱讀兩個選項，再作決定。'};
   return {title:progress.resolved<3?'前往下一個調查地點':!progress.deduced?'打開推理板，串起證物':'完成本章的實物謎題',text:'每章完成三處調查與證物推論即可前進；劇院另需解開機關。'};
  }
  return {title:s.flags.lightOff?'帶著能救的人離港':s.flags.disaster?'儀式已成形，尋找撤離的路':s.flags.rescued?'查明如何停止燈塔的光':'尋找妹妹的去向',text:s.clues.length?'查看證物，選擇下一步。地圖可前往其他已開放地點。':'先從妹妹留下的房間開始。核心線索不會因一次失敗消失。'};
 }
 function hud(s){const p=s.player,d=Pressure.describe(s),critical=p.hp<=Math.ceil(p.maxHp/3),late=s.pressure.stage===3;const stat=(name,value,max,type)=>'<div class="hud-stat '+type+'" aria-label="'+name+' '+value+' / '+max+'"><span>'+icon(type==='health'?'heart':'eye')+name+'</span><strong>'+value+'<small> / '+max+'</small></strong><i style="--fill:'+Math.round(value/max*100)+'%" aria-hidden="true"></i></div>';return '<section class="mission-hud '+(critical?'injured':'')+'" aria-label="重要狀態">'+stat('生命',p.hp,p.maxHp,'health')+stat('理智',p.san,99-p.skills.mythos,'sanity')+'<div class="hud-supply"><span>補給</span><strong>'+s.pressure.supplies+'<small> / 12</small></strong></div><div class="hud-deadline '+(late?'urgent':'')+'"><span>'+icon('clock')+(late?'強制撤離倒數':'調查窗口')+'</span><strong>'+(late?d.escape:d.remaining)+'<small> 分鐘</small></strong><small>'+esc(late?'期限用盡將結束調查':'下一階段：'+Math.max(0,d.next)+' 分鐘後')+'</small></div><span class="hud-reading">閱讀不耗時</span></section>';}
 function tools(s){const items=[['sheet','角色卡','能力、技能與隨身物品'],['npcs','人物與關係','查看已遇見的人物'],['journal','完整調查紀錄','回顧對話、事件與選擇'],['rolls','骰子紀錄','檢定門檻、候選與結果'],...(s.story?[['notes','私人筆記','記下你的推論與疑點']]:[]),['export','匯出進度備份','將調查保存成 JSON 檔案']];return '<div class="eyebrow">INVESTIGATOR TOOLKIT</div><h2>調查工具</h2><div class="tool-grid">'+items.map(([id,title,detail])=>'<button data-ui="'+id+'"><b>'+title+'</b><small>'+detail+'</small></button>').join('')+'</div>'+(s.story?'<div class="tool-footer"><button data-ui="rest" '+(s.player.hp>=s.player.maxHp||s.healthCare[s.chapter]||s.support<1||s.combat||s.pending||s.finale||s.ending||s.flags.dying||Pressure.blocked(s)?'disabled':'')+'>現場急救 · 1 支援</button><button data-ui="evacuate" '+(s.combat||s.pending||s.ending?'disabled':'')+'>結束調查，撤離</button></div>':'')+'<p class="subtle">查閱資料不會推進世界時間。治療與撤離會影響調查。</p>';}
 function mount(app,s){
  current={app,state:s};header();doc.documentElement.classList.add('in-investigation');observeDice(s);
  const layout=app.querySelector('.workspace');if(!layout||layout.dataset.cinematic)return;layout.dataset.cinematic='true';
  layout.classList.add('cinema-layout');layout.dataset.story=s.story||'fog';
  if(!s.ending){const summary=doc.createElement('div');summary.innerHTML=hud(s);app.insertBefore(summary.firstElementChild,layout);}
  const story=layout.querySelector('.story-column'),heading=story.querySelector('.scene-heading'),art=story.querySelector('.card-art, .scene-art');
  const hero=doc.createElement('section');hero.className='scene-hero';hero.setAttribute('aria-label','目前調查場景');
  if(art){art.classList.add('scene-hero-art');hero.appendChild(art);}if(heading)hero.appendChild(heading);layout.insertBefore(hero,layout.firstChild);
  const sidebar=layout.querySelector('.sidebar'),right=layout.querySelector('.rightbar'),choices=story.querySelector(':scope > .choices'),chapter=story.querySelector('.chapter-ready'),pressure=story.querySelector('.pressure-panel');
  let toolbar=story.querySelector('.case-actions');if(!toolbar){toolbar=doc.createElement('div');toolbar.className='case-actions';toolbar.innerHTML='<button data-ui="journal">調查紀錄</button><button data-ui="npcs">人物</button>';story.insertBefore(toolbar,story.firstChild);}
  toolbar.querySelectorAll('button').forEach(b=>{if(!['board','puzzles','dialogue','journal'].includes(b.dataset.ui))b.remove();});
  const more=doc.createElement('button');more.dataset.ui='tools';more.className='more-tools';more.innerHTML=icon('book')+'調查工具';toolbar.appendChild(more);
  const goal=objective(s),objectiveCard=doc.createElement('section');objectiveCard.className='current-objective';objectiveCard.innerHTML='<span class="eyebrow">目前目標</span><h2>'+esc(goal.title)+'</h2><p>'+esc(goal.text)+'</p>';story.insertBefore(objectiveCard,toolbar.nextSibling);
  if(sidebar){sidebar.querySelector('.meters')?.setAttribute('aria-hidden','true');const label=doc.createElement('div');label.className='rail-heading';label.textContent='調查員與地圖';sidebar.insertBefore(label,sidebar.firstChild);}
  if(right&&choices&&!s.ending){const notes=doc.createElement('details');notes.className='field-notebook';const title=doc.createElement('summary');title.textContent='證物筆記與檢定 · '+s.clues.length+' 份';notes.appendChild(title);const contents=doc.createElement('div');while(right.firstChild)contents.appendChild(right.firstChild);notes.appendChild(contents);right.classList.add('action-rail');right.innerHTML='<div class="console-header"><span class="eyebrow">YOUR NEXT MOVE</span><h2>'+(s.combat?'戰鬥行動':Pressure.blocked(s)?'突發事件':'你打算怎麼做？')+'</h2><span class="console-hint">選擇會立即執行，請先留意時間與代價。</span></div>';const scroll=doc.createElement('div');scroll.className='console-scroll';scroll.appendChild(choices);if(chapter)scroll.appendChild(chapter);if(pressure)scroll.appendChild(pressure);scroll.appendChild(notes);right.appendChild(scroll);}
  const dock=app.querySelector('.action-dock');if(dock){dock.querySelector('[data-ui="action-menu"]')?.setAttribute('aria-keyshortcuts','I');dock.querySelector('[data-ui="quick-map"]')?.setAttribute('aria-keyshortcuts','M');const toolsButton=doc.createElement('button');toolsButton.dataset.ui='tools';toolsButton.className='dock-tools';toolsButton.innerHTML=icon('book')+'工具';dock.appendChild(toolsButton);}
 }
 function decorate(app){header();if(app.querySelector('.workspace'))return;current=null;doc.documentElement.classList.remove('in-investigation');const login=app.querySelector('.login');if(login&&!login.dataset.cinematic){login.dataset.cinematic='true';login.children[0].classList.add('login-story');const backdrop=doc.createElement('div');backdrop.className='login-backdrop';backdrop.setAttribute('aria-hidden','true');backdrop.innerHTML=FieldUI.art('fog');login.prepend(backdrop);}
  const library=app.querySelector('.hub-library');if(library&&!library.dataset.cinematic){library.dataset.cinematic='true';const cards=Array.from(library.querySelectorAll('.story-card')),candidate=cards.find(c=>c.querySelector('[data-new]')&&!c.textContent.includes('已完成：'))||cards[0],button=candidate?.querySelector('[data-story]');if(button){const hero=doc.createElement('section');hero.className='library-spotlight';hero.innerHTML='<div class="spotlight-art" aria-hidden="true">'+FieldUI.art(button.dataset.story)+'</div><div class="spotlight-copy"><span class="eyebrow">THE INVESTIGATOR ARCHIVES</span><h2>每個答案，<br>都留下另一道陰影。</h2><p>追查失蹤的人、讀懂被藏起的證物。<br>下一步，由你決定。</p><button class="primary" data-story="'+button.dataset.story+'">'+(candidate.querySelector('[data-new]')?'繼續調查':'從這裡開始')+' · '+esc(candidate.querySelector('h2').textContent)+icon('arrow')+'</button><span class="spotlight-note">五份原創案件 · 單人調查 · 進度自動保存</span></div>';library.insertBefore(hero,library.querySelector('.timeline'));}}
 }
 doc.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.textSizeChoice){prefs.text=button.dataset.textSizeChoice;applyPrefs(true);}const action=button.dataset.cinema;if(action==='settings')settings();if(action==='contrast'||action==='dice'){prefs[action]=!prefs[action];applyPrefs(true);}if(action==='fullscreen')fullscreen();if(action==='close-settings')doc.getElementById('display-options').close();if(action==='skip-dice')finishAnimation();if(action==='close-dice')diceDialog().close();if(action==='disable-dice'){prefs.dice=false;applyPrefs(true);diceDialog().close();}if(action==='next-dice'){if(++diceIndex<diceBatch.length)renderDice();else diceDialog().close();}});
 doc.addEventListener('keydown',event=>{if(!current||event.repeat||event.ctrlKey||event.altKey||event.metaKey||doc.querySelector('dialog[open]')||event.target.closest('input,textarea,select,[contenteditable="true"]'))return;const command={i:'action-menu',m:'quick-map',j:'journal'}[event.key.toLowerCase()];if(!command)return;const button=current.app.querySelector('[data-ui="'+command+'"]');if(button&&!button.disabled){event.preventDefault();button.click();}});
 applyPrefs();header();const app=doc.getElementById('hub-app')||doc.getElementById('app');if(app){new MutationObserver(()=>decorate(app)).observe(app,{childList:true});decorate(app);}
 if(root.frameElement?.id==='legacy-game')doc.documentElement.classList.add('embedded-investigation');
 if(app){const syncLegacy=()=>doc.documentElement.classList.toggle('legacy-view',!!app.querySelector('#legacy-game'));new MutationObserver(syncLegacy).observe(app,{childList:true});syncLegacy();}
 root.Cinema={mount,tools,objective,icon,settings,fullscreen};
})(window);
