(function(root){'use strict';
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={fog:'霧港燈塔與渡輪碼頭',asylum:'白榆療養院雨中的中庭',train:'夜霧中駛來的無名列車',tide:'退潮露出的古老海城',theatre:'留著面具與紙花的空劇院'};
 function art(key){return '<img class="story-illustration" src="'+(root.SceneArt?.[key]||'assets/'+key+'.png')+'" alt="'+names[key]+'" decoding="async">';}
 function panel(s){if(s.ending)return '';const p=Pressure.ensure(s),d=Pressure.describe(s);return '<section class="pressure-panel stage-'+p.stage+'" aria-label="危機倒數"><div class="row spread"><strong>'+d.title+' · '+d.stage+'</strong><span>補給 '+p.supplies+'/12'+(p.supplies===0?' · 技能受1顆懲罰骰':'')+'</span></div><progress max="'+p.budget+'" value="'+Math.min(p.budget,p.spent)+'" aria-label="本章已用行動時間"></progress><p>調查窗口剩 '+d.remaining+' 分鐘'+(p.stage===3?' · 強制撤離剩 '+d.escape+' 分鐘':'')+'。<b>再 '+Math.max(0,d.next)+' 分鐘：'+d.effect+'。</b></p><small>僅行動推進時間，閱讀與關閉視窗不耗時。'+(p.breaches?' 已超時 '+p.breaches+' 次，後續窗口縮短。':'')+'</small></section>';}
 function button(id,title,hint,disabled=false){return '<button class="choice" data-pressure="'+id+'" '+(disabled?'disabled':'')+'><span class="words"><b>'+title+'</b><small>'+hint+'</small></span></button>';}
 function choices(s){const p=Pressure.ensure(s);if(s.ending||s.combat||s.pending||s.flags.dying)return '';const ev=Pressure.events.find(e=>e.id===p.pending);if(ev){return '<div class="incident"><span class="eyebrow">突發事件 / INCIDENT</span><h3>'+esc(ev.title)+'</h3><p>'+esc(ev.text)+'</p><p class="subtle">'+esc(ev.detail)+'</p>'+button('risk','冒險應對',Fog.SKILLS[ev.skill][0]+' '+s.player.skills[ev.skill]+' · 10分鐘；失敗補給－1、警戒＋1'+(ev.kind==='combat'?'，並觸發戰鬥':''))+button('careful','使用物資，穩妥處理','補給－1 · 25分鐘 · 保證化解並取得協助',p.supplies<1)+button('leave','立即離開','5分鐘 · '+(s.story?(ev.kind==='trust'?'信任－1':'警戒＋1'):'對方提高戒心'))+'</div>';}
  if(s.finale)return '';return '<details class="field-opportunities"><summary>補給與限時機會'+(p.opportunity==='open'?' · 聯絡窗口仍開放':'')+'</summary>'+(p.opportunity==='open'?button('opportunity','趕上聯絡窗口',(s.story?'支援＋2、':'')+'補給＋1 · 20分鐘 · 本章一次',p.spent+20>Math.ceil(p.budget/2)):'<p class="subtle">本章聯絡機會'+(p.opportunity==='taken'?'已使用。':'已結束。')+'</p>')+button('resupply','花時間整備補給','40分鐘，補給＋2；補給達5後不可再整備',p.supplies>=5)+'</details>';
 }
 function dock(s){if(s.ending)return '';const d=Pressure.describe(s);return '<nav class="action-dock" aria-label="隨時行動"><span class="dock-status">'+(Pressure.blocked(s)?'有突發事件待處理':d.stage)+'<small>'+d.remaining+' 分鐘窗口 · 補給 '+s.pressure.supplies+'</small></span><button class="primary" data-ui="action-menu">'+(s.combat?'戰鬥行動':Pressure.blocked(s)?'處理事件':'選擇下一步')+'</button><button data-ui="quick-map">地圖</button><button data-ui="'+(s.story?'board':'journal')+'">'+(s.story?'推理':'紀錄')+'</button></nav>';}
 root.FieldUI={art,panel,choices,dock};
})(globalThis);
